# Generated by Django 3.1.7 on 2021-04-28 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uprofile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='email',
            new_name='intro',
        ),
    ]
