# Generated by Django 3.1.7 on 2021-05-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweets',
            name='retweets',
        ),
        migrations.AddField(
            model_name='tweets',
            name='retweeted',
            field=models.BooleanField(default=False),
        ),
    ]
