# Generated by Django 3.1.7 on 2021-05-03 21:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweets', '0003_auto_20210503_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweets',
            name='retweeted',
        ),
        migrations.AddField(
            model_name='tweets',
            name='retweeted',
            field=models.ManyToManyField(blank=True, related_name='retweeter', to=settings.AUTH_USER_MODEL),
        ),
    ]
