# Generated by Django 3.1.7 on 2021-05-04 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweets', '0004_auto_20210503_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='comment_time',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='retweets',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='tweet',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='user',
        ),
        migrations.AddField(
            model_name='comments',
            name='commenter',
            field=models.ManyToManyField(blank=True, related_name='commenter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comments',
            name='main_tweet',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='maintweet', to='tweets.tweets'),
        ),
        migrations.AddField(
            model_name='comments',
            name='your_tweet',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='tweets.tweets'),
        ),
    ]
