# Generated by Django 3.1.7 on 2021-05-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0006_remove_comments_commenter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='your_tweet',
        ),
        migrations.AddField(
            model_name='comments',
            name='your_tweet',
            field=models.ManyToManyField(blank=True, default=None, related_name='comment', to='tweets.Tweets'),
        ),
    ]
