# Generated by Django 3.1.7 on 2021-05-04 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0007_auto_20210504_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentsrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commented_tweet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commentedtweet', to='tweets.tweets')),
                ('parent_tweet', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tweets.tweets')),
            ],
        ),
    ]
