# Generated by Django 3.1.7 on 2021-05-05 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0008_commentsrel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsrel',
            name='commented_tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentedtweet', to='tweets.tweets'),
        ),
        migrations.AlterField(
            model_name='commentsrel',
            name='parent_tweet',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tweets.tweets'),
        ),
    ]
