# Generated by Django 3.1.7 on 2021-05-06 20:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0009_auto_20210505_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='tweet',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
