# Generated by Django 3.1.7 on 2021-05-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0010_auto_20210506_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='tweet',
            field=models.CharField(max_length=10000),
        ),
    ]
