# Generated by Django 3.1.7 on 2021-05-01 06:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0002_auto_20210501_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='follower',
            field=models.ManyToManyField(blank=True, related_name='personfollower', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='social',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='personfollowing', to=settings.AUTH_USER_MODEL),
        ),
    ]
