# Generated by Django 3.1.7 on 2021-05-01 18:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0005_auto_20210501_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='follower',
        ),
        migrations.AddField(
            model_name='follower',
            name='follower',
            field=models.ManyToManyField(related_name='personfollower', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='following',
            name='following',
        ),
        migrations.AddField(
            model_name='following',
            name='following',
            field=models.ManyToManyField(related_name='personfollowing', to=settings.AUTH_USER_MODEL),
        ),
    ]
